
INSERT INTO pokemon_attack
VALUES  (20000, 'Normal moves are not very effective against: Rock & Steel'),
        (20000, 'Normal moves have no effect on: Ghost').
        (20001, 'Fire moves are super-effective against: Grass, Ice, Bug and Steel');

INSERT INTO pokemon_defence
VALUES ();

INSERT INTO pokemon
VALUES  ('Caterpie'),
        ('Metapod'),
        ('Butterfree'),
        ('Weedle'),
        ('Kakuna'),
        ('Beedrill'),
        ('Pidgey'),
        ('Pidgeotto'),
        ('Pidgeot'),
        ('Rattata'),
        ('Raticate'),
        ('Spearow'),
        ('Fearow'),
        ('Ekans'),
        ('Arbok'),
        ('Pikachu'),
        ('Raichu'),
        ('Sandshrew'),
        ('Sandslash'),
        ('Nidoran'),
        ('Nidorina'),
        ('Nidoqueen'),
        ('Nidorino'),
        ('Nidoking'),
        ('Clefairy'),
        ('Clefable'),
        ('Vulpix'),
        ('Ninetales'),
        ('Jigglypuff'),
        ('Wigglytuff'),
        ('Zubat'),
        ('Golbat'),
        ('Oddish'),
        ('Gloom'),
        ('Vileplume'),
        ('Paras'),
        ('Parasect'),
        ('Venonat'),
        ('Venomoth'),
        ('Diglett'),
        ('Dugtrio'),
        ('Meowth'),
        ('Persian'),
        ('Psyduck'),
        ('Golduck'),
        ('Mankey'),
        ('Primeape'),
        ('Growlithe'),
        ('Arcanine'),
        ('Poliwag'),
        ('Poliwhirl'),
        ('Poliwrath'),
        ('Abra'),
        ('Kadabra'),
        ('Alakazam'),
        ('Machop'),
        ('Machoke'),
        ('Machamp'),
        ('Bellsprout'),
        ('Weepinbell'),
        ('Victreebell'),
        ('Tentacool'),
        ('Tentacruel'),
        ('Geodude'),
        ('Graveler'),
        ('Golem'),
        ('Ponyta'),
        ('Rapidash'),
        ('Slowpoke'),
        ('Slowbro'),
        ('Magnemite'),
        ('Magneton'),
        ('Farfetch\'d'),
        ('Doduo'),
        ('Dodrio'),
        ('Seel'),
        ('Dewgong'),
        ('Grimer'),
        ('Muk'),
        ('Shellder'),
        ('Cloyster'),
        ('Gastly'),
        ('Haunter'),
        ('Gengar'),
        ('Onix'),
        ('Drowzee'),
        ('Hypno'),
        ('Krabby'),
        ('Kingler'),
        ('Voltorb'),
        ('Electrode'),
        ('Exeggcute'),
        ('Exeggutor'),
        ('Cubone'),
        ('Marowak'),
        ('Hitmonlee'),
        ('Hitmonchan'),
        ('Lickitung'),
        ('Koffing'),
        ('Weezing'),
        ('Rhyhorn'),
        ('Rhydon'),
        ('Chansey'),
        ('Tangela'),
        ('Kangaskhan'),
        ('Horsea'),
        ('Seadra'),
        ('Goldeen'),
        ('Seaking'),
        ('Staryu'),
        ('Starmie'),
        ('Mr. Mime'),
        ('Scyther'),
        ('Jynx'),
        ('Electabuzz'),
        ('Magmar'),
        ('Pinsir'),
        ('Tauros'),
        ('Magikarp'),
        ('Gyarados'),
        ('Lapras'),
        ('Ditto'),
        ('Eevee'),
        ('Vaporeon'),
        ('Jolteon'),
        ('Flareon'),
        ('Porygon'),
        ('Omanyte'),
        ('Omanstar'),
        ('Kabuto'),
        ('Kabutops'),
        ('Aerodactyl'),
        ('Snorlax'),
        ('Articuno'),
        ('Zapdos', )
        ('Moltres'),
        ('Dratini'),
        ('Dragonair'),
        ('Dragonite'),
        ('Mewtwo'),
        ('Mew');

INSERT INTO abilities
VALUES ();

INSERT INTO evolution
VALUES ();

INSERT INTO pokemon_abilities
VALUES ();


http://pokemondb.net/type/fairy